### ISSUE TITLE
Rotating arrow

### ISSUE THREAD

**Issue by ivanpanasiuk** [grennis/ExpandableRecyclerView#1]
I have use your class for creating an expandable list and its work nice. I changed that arrow rotate 180 degrees, instead of 90, but now when i scroll down and scroll back (list have about 20 items) arrow is not in rotating position.

**Comment by grennis** [comment]
Take care that the arrow is set to the correct position when the header view holder is bound. Otherwise, when the header view is recycled for use again, the arrow rotation may not be correct. This is done here: https://github.com/grennis/ExpandableRecyclerView/blob/master/app/src/main/java/com/innodroid/expandablerecyclerdemo/ExpandableRecyclerAdapter.java#L119

It sounds like you may have moved/removed this code?

**Comment by ivanpanasiuk** [comment]
Thank for your quick reply. I have that code. To me it is not clear which
bind header method will be executed: from ExpandableRecyclerAdapter or
extend my class?

On 16 December 2015 at 14:25, Greg Ennis notifications@github.com wrote:

> Take care that the arrow is bound to the correct position when the header
> view holder is bound. Otherwise, when the header view is recycled for use
> again, the arrow rotation may not be correct. This is done here:
> https://github.com/grennis/ExpandableRecyclerView/blob/master/app/src/main/java/com/innodroid/expandablerecyclerdemo/ExpandableRecyclerAdapter.java#L119
> 
> It sounds like you may have moved/removed this code?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/grennis/ExpandableRecyclerView/issues/1#issuecomment-165104470
> .

## 

Ivan Panasiuk

**Comment by ivanpanasiuk** [comment]
I have copied https://github.com/grennis/ExpandableRecyclerView/blob/master/app/src/main/java/com/innodroid/expandablerecyclerdemo/ExpandableRecyclerAdapter.java#L119
to my bind in extended class and now its OK. I do not why I could not call super() at bind method in my class. (probably it will resolve the issue also)

Thanks

**Comment by grennis** [comment]
I fixed the sample app, in the people adapter the Header View Holder was not calling through to super.bind(...). Thank you for pointing that out!
