### ISSUE TITLE
Refresh ChildItems

### ISSUE THREAD

**Issue by venkatsys** [grennis/ExpandableRecyclerView#15]
Hello,

I have implemented the expandable Recycler view & its working fine. I am having a functionality that I need to refresh the child items with respect to parent item click. How to achieve it?

**Comment by grennis** [comment]
You can either override `handleClick` in your header view holder, override `toggleExpandedItems` in your adapter, and do whatever custom logic there that you need to.

**Comment by venkatsys** [comment]
Thanks for your kind reply. After I have override the toggleExpandedItems  method I am getting the parent item position. I have a toggle button in the header item & it contains mutiple child items.When the user changed the toggle state in the header item ,At the same time I need to change all the child items toggle state ex (true or false) with respect to that parent item toggle state. 

With that clicked parent item position I need to notify to all my child items.How to achieve it? I am hard to find the solution...

**Comment by grennis** [comment]
I think since you have the parent item position in toggleExpandedItems you can iterate over the next items (which will be your child items) until you get to the next header item.

**Comment by venkatsys** [comment]
Thanks for your kind reply.  
I have iterate all my parents and children in the list.In the toggleExpandedItems() method I have an position but how would I iterate the children items & also how will i get the reference of my child items in the toggleExpandedItems()  method. 

My requirement is  I need to get the Child position of that clicked parent position why because I have to change the toggle button state in the multiple child items. Once I clicked the parent position, I am changing  the background color of that parent item to, When I was call notifyitemposition(position) it will notify that position , At the same time the child items are not refreshed. When i was call notifydatasetchanged() method the child items are refreshed  but the background color is changed to default one.

**Comment by grennis** [comment]
I would do something like this

```
for (int i = position + 1; i < getItemCount() && getItemViewType(position) != TYPE_HEADER; i++) {
    // do something with child item at position i
}

```

**Comment by venkatsys** [comment]
Thanks for your kind reply. I have try with the above condition & am getting the below values.
position = 2  i.e parent item position
getItemCount() = 4 i.e total parent items
getItemViewType(position) = 1000 
for( int i = position + 1 ; i < getItemCount() && getItemViewType(position) != TYPE_HEADER ; i++){
         // am not getting the logs.
            Log.i("toggle","dddddddddd" + i);
        }

**Comment by grennis** [comment]
```
getItemCount() = 4 i.e total parent items
```

No, that's 4 total visible items including parents and children. Also, when you override toggleExpandedItems make sure you are calling super.toggleExpandedItems first, to make sure the new child items are added.

**Comment by venkatsys** [comment]
Many thanks for your kind reply.

Based on your example , When I have clicked the parent item called Associates It will display the children items however in the toggleExpandedItems(int position ,  boolean notify) method  am getting the below output,

position = 2
getItemCount() = 8 
getItemViewType(position)1000. Please help..

for( int i = position + 1 ; i < getItemCount() && getItemViewType(position) != TYPE_HEADER ; i++){
  // am not getting the logs. Log.i("toggle","dddddddddd" + i);
}

**Comment by grennis** [comment]
Sorry, I had a mistake in my sample code. getItemViewType(position) should not be called - it should be getItemViewType(i). Like this

```
for( int i = position + 1 ; i < getItemCount() && getItemViewType(i) != TYPE_HEADER ; i++) {
  }
```

**Comment by venkatsys** [comment]
Bro, Its working great When I was closed the expandable view it was triggered i.e I can see the logs and also printed the child position. Many thanks...

**Comment by grennis** [comment]
Sure, because after you called toggleExpandedItems the items have been collapsed! If the items are being collapsed, you should process them BEFORE you call super.toggleExpandedItems

**Comment by venkatsys** [comment]
sure, Many thanks...U have helped me a lot with your patience. Even though I have asked many doubts & questions U have quickly replied me and also given a quick solution. Thanks  a lot.....
