### ISSUE TITLE
OnGroupExpandListener & OnChildClickListener

### ISSUE THREAD

**Issue by aman-jham** [grennis/ExpandableRecyclerView#6]
How i get the OnGroupExpandListener() & OnChildClickListener() ?

**Comment by grennis** [comment]
In order to set the click listener, just do it as you normally would in a recycler adapter.

There isn't a way to set an expand/collapse handler right now, I would need to add it. How about a virtual method in HeaderViewHolder that you can override? That's probably how I will do it.

**Comment by aman007jham** [comment]
I done the click listener but now i am facing the issue in onChildItem position.

**Comment by grennis** [comment]
With the position you can get access to the data. See for example https://github.com/grennis/ExpandableRecyclerView/blob/master/app/src/main/java/com/innodroid/expandablerecyclerdemo/PeopleAdapter.java#L65 where the people adapter gets the  name of the person.

**Comment by grennis** [comment]
To know when groups are expanding or collapsing, just override `expandItems` and `collapseItems` in your adapter. The position is passed in as an argument.
